<?xml version="1.0" encoding="utf-8"?><Database Name="hercules_db" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=158.85.25.234;Initial Catalog=hercules_db;User ID=jonathan-desarrollo;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="hercules_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.loggers" Member="loggers">
    <Type Name="loggers">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LoggerType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LoggerSoftware" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LoggerSerialNumber" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LoggerSMSNumber" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LoggerGSMNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="OwnerAccount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastCallIn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RST" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SignalLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BatteryLevel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="LogRateMs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NetID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LAC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CellID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MastLongitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MastLatitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DataCount" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="LastMessageType" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CallFrequency" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="loggers_sites" Member="sites" ThisKey="ID" OtherKey="LoggerID" Type="sites" />
    </Type>
  </Table>
  <Table Name="dbo.sites" Member="sites">
    <Type Name="sites">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DatagateID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerAccount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SiteID" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="LatEast" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LongNorth" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HeightAOD" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LoggerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="quietdays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZoneID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="zone_sites" Member="zone" ThisKey="ZoneID" OtherKey="ID" Type="zone" IsForeignKey="true" />
      <Association Name="loggers_sites" Member="loggers" ThisKey="LoggerID" OtherKey="ID" Type="loggers" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.zone" Member="zone">
    <Type Name="zone">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ZoneName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="zone_sites" Member="sites" ThisKey="ID" OtherKey="ZoneID" Type="sites" />
    </Type>
  </Table>
  <Table Name="dbo.alarms" Member="alarms">
    <Type Name="alarms">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MessageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoggerSMSNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="AlarmText" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Association Name="alarmTypes_alarms" Member="alarmTypes" ThisKey="MessageID" OtherKey="AlarmTypeId" Type="alarmTypes" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.alarmTypes" Member="alarmTypes">
    <Type Name="alarmTypes">
      <Column Name="AlarmTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AlarmType" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="AlarmTypeCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Channel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="alarmTypes_alarms" Member="alarms" ThisKey="AlarmTypeId" OtherKey="MessageID" Type="alarms" />
    </Type>
  </Table>
</Database>