//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerculesSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarms
    {
        public int ID { get; set; }
        public int MessageID { get; set; }
        public string LoggerSMSNumber { get; set; }
        public string AlarmText { get; set; }
        public Nullable<bool> Acknowledged { get; set; }
    
        public virtual alarmTypes alarmTypes { get; set; }
    }
}
