//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerculesSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alarmTypes
    {
        public alarmTypes()
        {
            this.alarms = new HashSet<alarms>();
        }
    
        public int AlarmTypeId { get; set; }
        public string AlarmType { get; set; }
        public Nullable<int> AlarmTypeCode { get; set; }
        public Nullable<int> Channel { get; set; }
    
        public virtual ICollection<alarms> alarms { get; set; }
    }
}
