//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerculesSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.loggers = new HashSet<loggers>();
            this.users = new HashSet<users>();
        }
    
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<loggers> loggers { get; set; }
        public virtual ICollection<users> users { get; set; }
    }
}
