//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerculesSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hercules_dbEntities : DbContext
    {
        public hercules_dbEntities()
            : base("name=hercules_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<zone> zones2 { get; set; }
        public virtual DbSet<sites> sites { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<loggers> loggers { get; set; }
        public virtual DbSet<alarms> alarms { get; set; }
        public virtual DbSet<alarmTypes> alarmTypes { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<siteloggersassociations> siteloggersassociations { get; set; }
    }
}
