//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerculesSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sites
    {
        public int ID { get; set; }
        public Nullable<int> DatagateID { get; set; }
        public Nullable<int> OwnerAccount { get; set; }
        public string SiteID { get; set; }
        public string Address { get; set; }
        public string LatEast { get; set; }
        public string LongNorth { get; set; }
        public string HeightAOD { get; set; }
        public Nullable<int> LoggerID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> quietdays { get; set; }
        public int ZoneID { get; set; }
        public int CompanyID { get; set; }

        public bool WithLogger { get; set; }

       
        public virtual zone zone { get; set; }
    }
}
