//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerculesSystem.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
    
    public partial class users
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
         [Required]
         [Remote("UserValidation", "Validations", ErrorMessage = "User Already Exists")]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
         [Required]
         [Remote("EmailValidation", "Validations", ErrorMessage = "Email Already Exists", AdditionalFields = "InitialEmail")]
         [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }
        [Required]
        public string Mobile { get; set; }
        public int ParentAccount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<bool> LoggedIn { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Role { get; set; }
        public bool RecieveNotifications { get; set; }
        public Nullable<int> AlarmForwardingMethod { get; set; }
        public int CompanyID { get; set; }
        public bool Status { get; set; }
    
        public virtual company company { get; set; }
        public virtual roles roles { get; set; }
    }
}
