//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerculesSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public int ParentAccount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<bool> LoggedIn { get; set; }
        public string Photo { get; set; }
        public Nullable<int> Role { get; set; }
        public bool RecieveNotifications { get; set; }
        public Nullable<int> AlarmForwardingMethod { get; set; }
        public int CompanyID { get; set; }
    
        public virtual company company { get; set; }
        public virtual roles roles { get; set; }
    }
}
