//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerculesSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zone
    {
        public zone()
        {
            this.sites = new HashSet<sites>();
        }
    
        public int ID { get; set; }
        public string ZoneName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<sites> sites { get; set; }
    }
}
