//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerculesSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class zone
    {
        public zone()
        {
            this.sites = new HashSet<sites>();
        }
    
        public int ID { get; set; }

        [Required]
        [Remote("ZoneValidation", "Validations", ErrorMessage = "Zone Already Exists", AdditionalFields = "InitialZone")]  

        public string ZoneName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> Status { get; set; }

        public int AmountSite { get; set; }
        public virtual ICollection<sites> sites { get; set; }
    }
}
